/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidatorsRouteImport } from './routes/validators'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as IndexRouteImport } from './routes/index'

const ValidatorsRoute = ValidatorsRouteImport.update({
  id: '/validators',
  path: '/validators',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/governance': typeof GovernanceRoute
  '/proposals': typeof ProposalsRoute
  '/report': typeof ReportRoute
  '/validators': typeof ValidatorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/governance': typeof GovernanceRoute
  '/proposals': typeof ProposalsRoute
  '/report': typeof ReportRoute
  '/validators': typeof ValidatorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/governance': typeof GovernanceRoute
  '/proposals': typeof ProposalsRoute
  '/report': typeof ReportRoute
  '/validators': typeof ValidatorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecosystem'
    | '/governance'
    | '/proposals'
    | '/report'
    | '/validators'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecosystem'
    | '/governance'
    | '/proposals'
    | '/report'
    | '/validators'
  id:
    | '__root__'
    | '/'
    | '/ecosystem'
    | '/governance'
    | '/proposals'
    | '/report'
    | '/validators'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemRoute: typeof EcosystemRoute
  GovernanceRoute: typeof GovernanceRoute
  ProposalsRoute: typeof ProposalsRoute
  ReportRoute: typeof ReportRoute
  ValidatorsRoute: typeof ValidatorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validators': {
      id: '/validators'
      path: '/validators'
      fullPath: '/validators'
      preLoaderRoute: typeof ValidatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemRoute: EcosystemRoute,
  GovernanceRoute: GovernanceRoute,
  ProposalsRoute: ProposalsRoute,
  ReportRoute: ReportRoute,
  ValidatorsRoute: ValidatorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
